# Generated by Django 5.0.7 on 2024-11-22 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='school',
            name='scphone',
        ),
    ]
