# Generated by Django 5.0.7 on 2024-11-22 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_school_scphone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='stphone',
        ),
    ]
