# Generated by Django 5.0.7 on 2024-11-27 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_student_stphone'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='scloc',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='school',
            name='scprincipal',
            field=models.CharField(default='Hello', max_length=100),
        ),
    ]
